let cfg,token,user,mediaRecorder,chunks=[],started=0,tick,currentLead,audioCtx,analyser,anim,streamRef;
const $=id=>document.getElementById(id); const show=id=>['login','app','rec'].forEach(x=>$(x).classList.toggle('hidden',x!==id));
async function api(action,opts={}){const fd=opts.fd;let url=cfg.api+(cfg.api.includes('?')?'&':'?')+'action='+encodeURIComponent(action);if(opts.q)url+='&q='+encodeURIComponent(opts.q);const h={};if(token)h.Authorization='Bearer '+token;const r=await fetch(url,{method:fd?'POST':'GET',headers:h,body:fd});const j=await r.json().catch(()=>({ok:false,message:'Invalid server response.'}));if(r.status===401&&action!=='login'){await logout(false)}return j}
async function init(){cfg=await window.pmuk.cfg();token=cfg.token;user=cfg.user;makeBars();if(token&&user){$('who').textContent=user.name;show('app');await refreshAll()}else show('login')}
$('loginBtn').onclick=async()=>{const fd=new FormData();fd.append('email',$('email').value.trim());fd.append('password',$('password').value);$('loginMsg').className='';$('loginMsg').textContent='Signing in…';try{const j=await api('login',{fd});if(!j.ok){$('loginMsg').className='error';$('loginMsg').textContent=j.message;return}token=j.token;user=j.user;await window.pmuk.saveAuth(j);$('who').textContent=user.name;show('app');await refreshAll()}catch(e){$('loginMsg').className='error';$('loginMsg').textContent='Could not reach PMUK CRM: '+e.message}};
async function logout(call=true){if(call&&token)try{await api('logout')}catch{}token='';user=null;await window.pmuk.clearAuth();$('who').textContent='';show('login')};$('logout').onclick=()=>logout();
async function refreshAll(){await Promise.all([loadLeads(),loadLibrary(),loadPending()]);await stats()}
async function loadLeads(){const j=await api('leads',{q:$('search').value.trim()});if(!j.ok){$('leadList').innerHTML='<p class="error">'+esc(j.message)+'</p>';return}$('leadList').innerHTML=j.leads.map(l=>`<div class="lead"><div><b>${esc(l.full_name)}</b><div class="muted">${esc(l.stage||'No stage')} · ${esc(l.phone||'No phone')} ${l.assigned_employee_name?'· '+esc(l.assigned_employee_name):''}</div></div><button class="primary" data-id="${l.id}">Record call</button></div>`).join('')||'<p class="muted">No leads found.</p>';[...document.querySelectorAll('[data-id]')].forEach(b=>b.onclick=()=>start(j.leads.find(l=>String(l.id)===b.dataset.id)))}
$('refresh').onclick=refreshAll;let searchTimer;$('search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(loadLeads,300)};
function makeBars(){const v=$('visual');for(let i=0;i<34;i++){const b=document.createElement('div');b.className='bar';v.appendChild(b)}}
function animateBars(){if(!analyser)return;const data=new Uint8Array(analyser.frequencyBinCount);analyser.getByteFrequencyData(data);const bars=[...document.querySelectorAll('.bar')];bars.forEach((b,i)=>{const x=data[Math.floor(i*data.length/bars.length)]||0;b.style.height=(10+(x/255)*72)+'px'});anim=requestAnimationFrame(animateBars)}
async function start(l){currentLead=l;chunks=[];try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});streamRef=stream;audioCtx=new AudioContext();analyser=audioCtx.createAnalyser();analyser.fftSize=128;audioCtx.createMediaStreamSource(stream).connect(analyser);animateBars();const mime=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';mediaRecorder=new MediaRecorder(stream,{mimeType:mime});mediaRecorder.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data)};mediaRecorder.start(5000);started=Date.now();$('leadName').textContent=l.full_name;$('leadStage').textContent=l.stage||'';$('recStatus').textContent='Recording audio · the completed call will remain saved on this PC';show('rec');tick=setInterval(updateTimer,250)}catch(e){alert('Microphone could not be opened: '+e.message)}}
function updateTimer(){let s=Math.floor((Date.now()-started)/1000);$('timer').textContent=[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,'0')).join(':')}
$('stop').onclick=async()=>{if(!mediaRecorder)return;$('stop').disabled=true;$('recStatus').textContent='Stopping and saving safely to this PC…';await new Promise(res=>{mediaRecorder.addEventListener('stop',res,{once:true});mediaRecorder.stop()});clearInterval(tick);cancelAnimationFrame(anim);if(streamRef)streamRef.getTracks().forEach(t=>t.stop());if(audioCtx)await audioCtx.close().catch(()=>{});const duration=Math.max(1,Math.round((Date.now()-started)/1000));const blob=new Blob(chunks,{type:mediaRecorder.mimeType||'audio/webm'});const bytes=[...new Uint8Array(await blob.arrayBuffer())];const m=await window.pmuk.saveRecording({bytes,mime:blob.type,lead:currentLead,duration,answered:'',result:'Other',notes:'Recorded with PMUK Windows Recorder.'});$('recStatus').textContent='Saved locally ✓ Uploading to CRM…';try{await uploadOne(m)}catch(e){}show('app');$('stop').disabled=false;await refreshAll()};
async function uploadOne(m){const full=await window.pmuk.read(m.id);const blob=new Blob([new Uint8Array(full.bytes)],{type:full.mime});const fd=new FormData();fd.append('lead_id',full.lead.id);fd.append('duration_seconds',full.duration);fd.append('result',full.result||'Other');fd.append('notes',full.notes||'Recorded with PMUK Windows Recorder.');fd.append('recording',blob,'PMUK-'+full.lead.id+'-'+full.id+'.webm');try{const j=await api('upload',{fd});if(j.ok){await window.pmuk.markUploaded(m.id,j.call_id);return true}throw new Error(j.message||'Upload failed')}catch(e){await window.pmuk.markFailed(m.id,e.message);throw e}}
async function loadLibrary(){let list=await window.pmuk.list();const q=$('recordingSearch').value.trim().toLowerCase();if(q)list=list.filter(m=>(m.lead?.full_name||'').toLowerCase().includes(q));$('recordingList').innerHTML=list.length?list.map(m=>recordingRow(m,true)).join(''):'<p class="muted">No recordings saved on this PC yet.</p>';wireRecordingButtons(list)}
function recordingRow(m,withAudio){const st=m.status||'pending';const label=st==='uploaded'?'Uploaded ✓':st==='failed'?'Upload failed':'Pending upload';return `<div class="recording"><div class="grow"><b>${esc(m.lead?.full_name||'Unknown lead')}</b><div class="muted">${new Date(m.created_at).toLocaleString()} · ${fmt(m.duration)} · ${esc(m.lead?.stage||'')}</div><div class="badge ${st==='uploaded'?'uploaded':st==='failed'?'failed':'pendingc'}">${label}${m.call_id?' · CRM call #'+m.call_id:''}</div></div><div class="actions">${withAudio?`<button class="soft" data-play="${m.id}">Play</button><button class="soft" data-save="${m.id}">Download / Save As</button><button class="soft" data-folder="${m.id}">Open folder</button>`:''}${st!=='uploaded'?`<button class="primary" data-up="${m.id}">Retry upload</button>`:''}</div></div>`}
function wireRecordingButtons(list){document.querySelectorAll('[data-play]').forEach(b=>b.onclick=async()=>{const m=await window.pmuk.read(b.dataset.play);const blob=new Blob([new Uint8Array(m.bytes)],{type:m.mime});const url=URL.createObjectURL(blob);const a=new Audio(url);a.play();a.onended=()=>URL.revokeObjectURL(url)});document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>window.pmuk.saveAs(b.dataset.save));document.querySelectorAll('[data-folder]').forEach(b=>b.onclick=()=>window.pmuk.openFolder(b.dataset.folder));document.querySelectorAll('[data-up]').forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent='Uploading…';try{await uploadOne(list.find(x=>x.id===b.dataset.up));await refreshAll()}catch(e){b.disabled=false;b.textContent='Retry upload';alert(e.message)}})}
async function loadPending(){const list=await window.pmuk.pending();$('pendingList').innerHTML=list.length?list.map(m=>recordingRow(m,false)).join(''):'<p class="muted ok">No pending recordings. Everything is synced.</p>';wireRecordingButtons(list)}
async function stats(){const list=await window.pmuk.list();const today=new Date().toDateString();const isToday=m=>new Date(m.created_at).toDateString()===today;$('sToday').textContent=list.filter(isToday).length;$('sUploaded').textContent=list.filter(m=>isToday(m)&&m.status==='uploaded').length;$('sPending').textContent=list.filter(m=>(m.status||'pending')==='pending').length;$('sFailed').textContent=list.filter(m=>m.status==='failed').length}
function fmt(s){s=Number(s)||0;return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,'0')).join(':')}
$('recordingSearch').oninput=loadLibrary;$('openRecordingFolder').onclick=async()=>{const list=await window.pmuk.list();if(list[0])window.pmuk.openFolder(list[0].id)};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.pane').forEach(p=>p.classList.add('hidden'));$(b.dataset.tab).classList.remove('hidden')});
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
init();
